sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t pathas1126/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true pathas1126/docker-react-app yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-281318957201
  bucket_path: docker-react-app
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
