sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t pathas1126/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true pathas1126/docker-react-app yarn test -- --coverage

after_success:
  - echo "Test Success"
